#!/bin/bash
#Use this script to replace yellow in EPS files to an orange-brown color.
#Especially useful for those EPS output files generated by gnuplot.
#See: http://david-white.myzen.co.uk/gnuplotNotes.html
sed -i 's/^LT5/LT7/g' $1
